name: Build and push CI image

on:
  schedule:
    - cron: '0 0 15 * *'  # Runs at 00:00 UTC on the 15th day of each month
  workflow_dispatch:

jobs:
  # Docker build
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile.custom
          tags: ghcr.io/${{ github.actor }}/ci-strategy-backtesting:latest
          cache-from: type=gha,mode=inline,scope=ci-strategy-backtesting
          cache-to: type=gha,mode=max,scope=ci-strategy-backtesting
          push: true
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
